name = "thegallimaufry-website"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
FROM_EMAIL = "enquiries@thegallimaufry.show"
TO_EMAIL = "info@thegallimaufry.show"
BUZZSPROUT_PODCAST_ID = "1460611"